spring:
  datasource:
    url: jdbc:mysql://localhost:3306/amazon_crud_springboot
    username: root
    password: Csprasanna@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
